export const stock=[
    {
        id:1,
        price: 100,
        name: "Boule de campo",
        img: "https://i.ibb.co/h1NypFW/maxresdefault.jpg",
        description: "Pan redondo tipo campo elaborado con Masa Madre, harina integral orgánica de trigo molido a piedra, aceite de oliva extra virgen orgánico y sal marina.",
        category_id: 1,
    },
    {
        id:2,
        price: 120,
        name: "Batard",
        img: "https://i.ibb.co/FmTSVW6/pan-batard-masa-madre-1.jpg",
        description: "Pan con Masa Madre, elaborado con trigo y centeno y elevada hidratación. El cuidado proceso y la cocción en horno de solera, dan como resultado un pan de sabor intenso, gruesa corteza y excelente conservación. Sin aditivos.",
        category_id: 1,
    },
    {
        id:3,
        price: 500,
        name: "Masa madre",
        img: "https://i.ibb.co/YtSZyhP/Captura-de-Pantalla-2021-08-19-a-la-s-23-56-26.png",
        description: "Fermento de masa madre en frasco de 250g. Nuestro fermento está elaborado con harina y agua, sin ningún tipo de levadura añadida, ya que la propia harina contiene levaduras que provocan la fermentación de las masas de manera espontánea.",
        category_id: 1,
    },
    {
        id:4,
        price: 1300,
        name: "Banetton",
        img: "https://i.ibb.co/YP2vxyW/Baneton.jpg",
        description: "Recipiente de rafia forrado en lino de algodón. Los banettons sirven para hacer la segunda fermentación del pan, es decir para que se llene la masa de aire y a más a más dar una forma inicial. Una vez ya haya transcurrido el tiempo necesario se deberá extraer la masa del banneton, colocarla en la pala de panadero y a continuación en el horno bien caliente.",
        category_id: 2,
    },
    {
        id:5,
        price: 6500,
        name: "Dutch oven",
        img: "https://i.ibb.co/Ms672rj/dutch-oven.jpg",
        description: "El Dutch Oven u Horno Holandés Fournée es la pieza perfecta para aquellas cocciones que comienzan en la hornalla y se terminan en el horno. En el Dutch Oven Fournée horneá los mejores panes, logrando la humedad y el vapor perfecto y una corteza crujiente. Pero además, el diseño súper original de nuestro Horno Holandés aporta funciones extra pudiendo ser utilizada como cacerola o guisera.",
        category_id: 2,
    },
    {
        id:6,
        price: 300,
        name: "Cornet",
        img: "https://i.ibb.co/5cVfxNT/cornet.jpg",
        description: "Cornet de madera natural. Es un elemento sencillo, muy básico y simple pero que ofrece gran ayuda en la cocina. Nos ayuda a mezclar ingredientes para hacer masas, a cortarla, apurarla y recoger lo que queda en los bordes de un recipiente.",
        category_id: 2,
    },
    {
        id:7,
        price: 300,
        name: "Pan de avena y semillas",
        img: "https://i.ibb.co/BgV46P7/SDC13426.jpg",
        description: "Pan con Masa Madre, elaborado con trigo y centeno y elevada hidratación. El cuidado proceso y la cocción en horno de solera, dan como resultado un pan de sabor intenso, gruesa corteza y excelente conservación. Sin aditivos.",
        category_id: 1,
    },
    {
        id:8,
        price: 2300,
        name: "Balanza de cocina",
        img: "https://i.ibb.co/wBqGY34/D-NQ-NP-2-X-829017-MLA45584205362-042021-F.webp",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        category_id: 2,
    },
]


